language: php

php:
  - 5.6
  - 7.0
  - 7.1

before_script:
  - travis_retry composer self-update

before_install:
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "5.6" ]]; then composer require --dev --no-update phpunit/phpunit 5.7.5; fi

install:
  - travis_retry composer install --no-interaction --prefer-dist