language: php

php:
  - 5.6
  - 7.0
  - 7.1

install:
  - travis_retry composer install --no-interaction --prefer-dist

before_script:
  - travis_retry composer self-update

script:
  - vendor/bin/phpunit